kind: ConfigMap
apiVersion: v1
metadata:
  name: my-integration-timer-to-postgres-prop
  namespace: camel-k-test
immutable: false
data:
  application.properties: |
    prop.application.name=Mon application insert postgresql