apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: my-integration
spec:
  traits:
    mount:
      configs:
        configmap: my-integration-prop
  sources:
  - content: |
      import org.apache.camel.builder.RouteBuilder;

      public class Test extends RouteBuilder {
          @Override
          public void configure() throws Exception {
              from("timer:java?period=1500")
                  .setBody()
                      .simple("Hello Camel from ${routeId} [{{prop.application.name}}]")
                  .log("${body}");
          }
      }
    name: Test.java