kind: ConfigMap
apiVersion: v1
metadata:
  name: greetings-api-cm
  namespace: camel-k-test
data:
  greetings-api-cm.json: |
    {
      "openapi": "3.0.1",
      "info": {
        "title": "Greeting REST API",
        "version": "1.0"
      },
      "servers": [
        {
          "url": "/camel/"
        }
      ],
      "tags": [
        {
          "name": "greetings",
          "description": "Greeting to {name}"
        }
      ],
      "paths": {
        "/greetings/{name}": {
          "get": {
            "tags": [
              "greetings"
            ],
            "operationId": "greeting-api",
            "parameters": [
              {
                "name": "name",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "200": {
                "description": "Output type",
                "content": {
                  "*/*": {
                    "schema": {
                      "$ref": "#/components/schemas/Greetings"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "components": {
        "schemas": {
          "Greetings": {
            "type": "object",
            "properties": {
              "greetings": {
                "type": "string"
              }
            }
          }
        }
      }
    }
