kind: ConfigMap
apiVersion: v1
metadata:
  name: my-integration-prop
  namespace: camel-k-test
immutable: false
data:
  application.properties: |
    prop.application.name=Mon application of martel
    camel.k.logging.level = DEBUG