apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: my-integration
spec:
  sources:
  - content: |
      import org.apache.camel.builder.RouteBuilder;

      public class Test extends RouteBuilder {
          @Override
          public void configure() throws Exception {
              from("timer:java?period=1500")
                  .setBody()
                      .simple("Hello Camel from ${routeId} , ${headers}")
                  .log("${body}");
          }
      }
    name: Test.java