apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: my-integration-with-transf
spec:
  sources:
  - content: |
      import org.apache.camel.builder.RouteBuilder;

      public class Test extends RouteBuilder {
          @Override
          public void configure() throws Exception {
              from("timer:java?period=1500")
                  .routeId("Integration")
                  .setBody()
                      .simple("Hello Camel from ${routeId} , headers = ${headers}")
                  .log("le log est ${body}")
                  .to("log:my-integration-log?showAll=true&multiline=true");
          }
      }
    name: Test.java