kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    camel.apache.org/config.type: camel-properties
  name: kafka-my-topic-to-log-cm
  namespace: camel-k-test
data:
  application.properties: |
    kafka-not-secured-sink.bootstrapServeurs=my-cluster-kafka-kafka-bootstrap.kafka.svc:9092
    kafka-not-secured-sink.topic=my-topic