kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    camel.apache.org/config.type: camel-properties
  name: kafka-my-topic-to-log-cm
  namespace: camel-k-test
data:
  application.properties: |
    camel.kamelet.kafka-not-secured-source.bootstrapServers=my-cluster-kafka-kafka-bootstrap.kafka.svc:9093
    camel.kamelet.kafka-not-secured-source.topic=my-topic