kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    camel.apache.org/config.type: camel-properties
    camel.apache.org/pipe: timer-to-kafka-my-topic-argocd
    camel.apache.org/properties.type: application
  name: timer-to-kafka-my-topic-argocd-cm
  namespace: camel-k-test
data:
  application.properties: |
    camel.kamelet.kafka-not-secured-sink.bootstrapServers=my-cluster-kafka-kafka-bootstrap.kafka.svc:9092
    camel.kamelet.kafka-not-secured-sink.topic=my-topic
    camel.kamelet.timer-source.message=Hello world with pipe from github->ArgoCD
    camel.kamelet.timer-source.periode=5000