kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    camel.apache.org/config.type: camel-properties
    camel.apache.org/pipe: timer-to-kafka-my-topic-2
  name: timer-to-kafka-my-topic-2-cm
  namespace: camel-k-test
data:
  application.properties: |
    camel.kamelet.kafka-not-secured-sink.sink.bootstrapServeurs=my-cluster-kafka-kafka-bootstrap.kafka.svc:9092
    camel.kamelet.kafka-not-secured-sink.sink.topic=my-topic
    camel.kamelet.timer-source.source.message=Hello world with pipe 2
    camel.kamelet.timer-source.source.periode=5000