kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    camel.apache.org/config.type: camel-properties
    camel.apache.org/pipe: timer-to-kafka-my-topic-argocd
    camel.apache.org/properties.type: application
  name: timer-to-kafka-my-topic-argocd-cm
  namespace: camel-k-test
data:
  application.properties: |
    kafka-not-secured-sink.bootstrapServeurs=my-cluster-kafka-kafka-bootstrap.kafka.svc:9092
    kafka-not-secured-sink.topic=my-topic
    timer-source.message=Hello world with pipe from github->ArgoCD
    timer-source.periode=5000
  ownerReferences:
    - apiVersion: camel.apache.org/v1
      blockOwnerDeletion: true
      controller: true
      kind: Pipe
      name: timer-to-kafka-my-topic-argocd