apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: greetings-open-api-int
  annotations:
      trait.camel.apache.org/mount.configs: configmap:greetings-api-cm
spec:
  sources:
  - content: |
      import org.apache.camel.builder.RouteBuilder;

      public class Greetings extends RouteBuilder {
          @Override
          public void configure() throws Exception {
            from("direct:greetings-api")
                  .routeId("Integration greetings")
                  .setBody()
                      .simple("Hello Camel from ${routeId} , headers = ${headers}")
                  .log("le log est ${body}")
                  .to("log:my-integration-log?showAll=true&multiline=true");
          }
      }
    name: Greetings.java